package exceptionHandling.Finally;

public class Case6 {

	public static void main(String[] args) {
		
	
				
		
				//Case 6
				System.out.println("Case-6");
				try {
					
					int i=5/0;
					System.out.println("jakeer");
				}
				finally{
					
					System.out.println("finally-ArithmeticException");
					
				}
	}

}
